composeexample/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^workflows/', include('workflows.urls')),
    url(r'^', include('workflows.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

workflows/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'workflows'
urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^create/$', views.create, name='create'),
    url(r'^modeler/$', views.modeler, name='modeler'),
    url(r'^create/modeler/$', views.saveXML, name='saveXML'),
    url(r'^profileedit/$', views.profileEdit, name = 'profileedit'),
    url(r'^register_user/$', views.register_user, name='register_user'),
    url(r'^view_profile/$', views.view_profile, name='view_profile'),
    url(r'^profileDetail/$', views.profileDetail, name='profileDetail'),
    url(r'^job/$', views.job, name='job'),
    url(r'^announce/$', views.announce, name='announce'),
    url(r'^funding/$', views.funding, name='funding'),
    url(r'^(?P<workflow_id>[0-9]+)/$', views.editingWorkflow, name='editWorkflow'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workflows/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


# Create your models here.
from django.db import models

"""
class Arc(models.Model):

    connected_node = Node()
    def action(self):
        return "do something"

class Node(models.Model):
    title = models.CharField(max_length=100)
    arc = Arc()


"""


class StudentModel(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    profileLogo = models.FileField(default='')
    tittle = models.CharField(max_length=50,default='')
    userType = models.CharField(max_length=50, default='')
    firstName = models.CharField(max_length=100)
    lastName = models.CharField(max_length=100)
    dateOfBirth = models.CharField(max_length=50)
    department = models.CharField(max_length=50, default='')
    mobile = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    loopId = models.CharField(max_length=50,default='')
    facebookAddress = models.CharField(max_length=100)


    def __unicode__(self):
        return self.firstName


class StaffModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    profileLogo = models.FileField(default='')
    tittle = models.CharField(max_length=50,default='')
    userType = models.CharField(max_length=50, default='')
    firstName = models.CharField(max_length=100)
    lastName = models.CharField(max_length=100)
    dateOfBirth = models.CharField(max_length=50)
    department = models.CharField(max_length=50, default='')
    mobile = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    loopId = models.CharField(max_length=50,default='')
    facebookAddress = models.CharField(max_length=100)


class AlumniModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    profileLogo = models.FileField(default='')
    tittle = models.CharField(max_length=50,default='')
    userType = models.CharField(max_length=50, default='')
    firstName = models.CharField(max_length=100)
    lastName = models.CharField(max_length=100)
    dateOfBirth = models.CharField(max_length=50)
    department = models.CharField(max_length=50, default='')
    mobile = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    loopId = models.CharField(max_length=50,default='')
    facebookAddress = models.CharField(max_length=100)


class WorkflowTemplate(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    xml = models.TextField(default='')
    status = models.CharField(max_length=100,default="Unpublished")
    #start = models.ForeignKey(StartEvent)
    creator = models.ForeignKey(User,default=1)

workflows/forms.py
from django.contrib.auth.models import User
from django import forms

from .models import *


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class StudentForm(forms.ModelForm):
    class Meta:
        model = StudentModel

        fields = ['profileLogo',
                  'userType',
                  'tittle',
                  'firstName',
                  'lastName',
                  'dateOfBirth',
                  'department',
                  'mobile',
                  'email',
                  'loopId',
                  'facebookAddress',
                  ]

    def __init__(self, *args, **kwargs):
        super(StudentForm, self).__init__(*args, **kwargs)
        self.fields['loopId'].required = False
        self.fields['profileLogo'].required = False


class WorkflowTemplateForm(forms.ModelForm):
    class Meta:
        model = WorkflowTemplate

        fields = ['name',
                  'description',

                ]

workflows/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from .models import *
from django.views.decorators.csrf import csrf_exempt

from .forms import *

def editingWorkflow(request, workflow_id):
    if not request.user.is_authenticated():
        return render(request, 'workflows/login.html')
    else:
        user = request.user
        workflow = get_object_or_404(WorkflowTemplate, pk=workflow_id)
        return render(request, 'workflows/modeler.html', {'editingWorkflow': workflow, 'user': user})

def job(request):
   return render(request, "workflows/job.html")


def announce(request):
   return render(request, "workflows/announce.html")


def funding(request):
   return render(request, "workflows/funding.html")

def view_profile(request):
    return render(request, "workflows/view_profile.html")


def profileEdit(request):
    return render(request, 'workflows/profile-edit.html')

def create(request):
    form = WorkflowTemplateForm(request.POST or None)

    if form.is_valid():
        workflow = form.save(commit=False)
        workflow.creator = request.user
        workflow.save()
        request.session['workflowId'] = workflow.id
        return render(request, 'workflows/modeler.html')

    else:
        context = {
            "form": form,
        }
        return render(request, 'workflows/create.html', context)

@csrf_exempt
def saveXML(request):
    workflowId = request.session['workflowId']
    if request.is_ajax():
        if request.method == 'POST':
            workflow = WorkflowTemplate.objects.get(id=workflowId)
            workflow.xml = request.POST.get('userXml')
            workflow.save()
            user = request.user
            workflows = WorkflowTemplate.objects.filter(creator=user)
            return render(request, 'workflows/index.html', {'workflows': workflows})



def modeler(request):

    return render(request, "workflows/modeler.html")


def index(request):
    if not request.user.is_authenticated():
        return register(request)
    else:
        user = request.user
        workflows = WorkflowTemplate.objects.filter(creator=user)
        return render(request, 'workflows/index.html', {'workflows': workflows})


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'workflows/login.html', context)

@csrf_exempt
def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                user = request.user
                workflows = WorkflowTemplate.objects.filter(creator=user)
                return render(request, 'workflows/index.html', {'workflows': workflows})

            else:
                return render(request, 'workflows/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'workflows/login.html', {'error_message': 'Invalid login'})
    return render(request, 'workflows/login.html')


def register(request):
    form = UserForm(request.POST or None)

    print("helooooooo")
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'workflows/index.html')
    context = {
        "form": form,
    }
    return render(request, 'workflows/register.html', context)


#User edit profile
def register_user(request):
    if not request.user.is_authenticated():
        return redirect('/register')
    else:
        form = StudentForm(request.POST or None, request.FILES or None)
        context = {
            "form": form,
        }
        if form.is_valid():
            student = form.save(commit=False)

            student.user = request.user
            student.profileLogo = request.FILES['profileLogo']

            student.save()
            return render(request, 'workflows/index.html', context)

        return render(request, 'workflows/profile-edit.html', context)


def profileDetail(request):
    if not request.user.is_authenticated():
        return render(request, 'workflows/login.html')
    else:

        user = request.user
        try:
            student = StudentModel.objects.get(user=user)
        except StudentModel.DoesNotExist:
            student = {}


        print(student)

        return render(request, 'workflows/view_profile.html', {'student': student})


def job(request):
    return render(request, "workflows/job.html")

def announce(request):
    return render(request, "workflows/announce.html")

def funding(request):
    return render(request, "workflows/funding.html")
'''

def profileDetail(request, user):
    if not request.user.is_authenticated():
        return render(request, 'workflows/login.html')
    else:
        user = request.user
        album = get_object_or_404(StudentModel, pk=user)
        return render(request, 'workflows/view_Profile.html', {'user': user})



def profileDetail(request):
  if request.method == 'GET':
    form = StudentForm(request.GET)
    if form.is_valid():
        return render(request, 'workflows/view_Profile.html')
  else:
    form = StudentForm()



def post_create(request):
    form =  StudentModel(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        print (form.cleaned_data.get("firstname"))
        instance.save()

        context = {
            "form":  form,
        }

        return render(request,"post_form.html",context)
'''

workflows/templates/workflows/base.html
 <!-- FlatFy Theme - Andrea Galanti /-->
<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if IE 9]>    <html class="no-js ie9" lang="en"> <![endif]-->
<!--[if gt IE 9]><!-->
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="Flatfy Free Flat and Responsive HTML5 Template ">
    <meta name="author" content="">

    <title>Workflows – An automate workflows engine for everyone!</title>

    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom Google Web Font -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Arvo:400,700' rel='stylesheet' type='text/css'>

    <!-- Custom CSS-->
     <link href="{% static 'css/general.css' %}" rel="stylesheet">

	 <!-- Owl-Carousel -->
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
	<link href="{% static 'css/owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'css/owl.theme.css' %}" rel="stylesheet">
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
	<link href="{% static 'css/animate.css' %}" rel="stylesheet">

	<!-- Magnific Popup core CSS file -->
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

	<script src="{% static 'js/modernizr-2.8.3.min.js' %}"></script>  
    <!-- Modernizr /-->  <!-- Modernizr /-->
	<!--[if IE 9]>
		<script src="js/PIE_IE9.js"></script>
	<![endif]-->
	<!--[if lt IE 9]>
		<script src="js/PIE_IE678.js"></script>
	<![endif]-->

	<!--[if lt IE 9]>
		<script src="js/html5shiv.js"></script>
	<![endif]-->


    <style>

.navbar-default
{
   position: fixed;
   top: 0px;
}

    </style>

</head>

<body id="home">

	<!-- Preloader -->
	<div id="preloader">
		<div id="status"></div>
	</div>

	<!-- NavBar-->
	<nav class="navbar-default" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'workflows:register' %}">{% block title %}Workflows Engine{% endblock %}</a>
			</div>

			<div class="collapse navbar-collapse navbar-right navbar-ex1-collapse">
				<ul class="nav navbar-nav">

					         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'workflows:profileedit' %}">Edit Profile</a></li>
            <li><a href="{% url 'workflows:profileDetail' %}">View Profile</a></li>
            <li><a href="{% url 'workflows:index' %}">My Workflow</a></li>

          </ul>
        </li>

                    <!-- <li class="menuItem"><a href="#whatis"> Member </a></li> -->


					<li class="menuItem"><a href="{% url 'workflows:logout_user' %}">Logout</a></li>
				</ul>
			</div>

		</div>
	</nav>




	<!-- FullScreen -->
   {% block body %}
	{% endblock %}



	<!-- Banner Download -->
	<!--

	<div id="downloadlink" class="banner">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-md-offset-3 text-center wrap_title">
				<h2>Download Free</h2>
				<p class="lead" style="margin-top:0">Pay with a Tweet</p>
				<p><a class="btn btn-embossed btn-primary view" role="button">Free Download</a></p>
			 </div>
			</div>
		</div>
	</div>
	-->

    <footer>

      <div class="container">
        <div class="row">

            <!--
          <div class="col-md-7">


            <h3 class="footer-title">Follow Me!</h3>
            <p>Vuoi ricevere news su altri template?<br/>
              Visita Andrea Galanti.it e vedrai tutte le news riguardanti nuovi Theme!<br/>
              Go to: <a  href="http://andreagalanti.it" target="_blank">andreagalanti.it</a>
            </p>


			<a rel="cc:attributionURL" href="http://www.andreagalanti.it/flatfy"
		   property="dc:title">Flatfy Theme </a> by
		   <a rel="dc:creator" href="http://www.andreagalanti.it"
		   property="cc:attributionName">Andrea Galanti</a>
		   is licensed to the public under
		   <BR>the <a rel="license"
		   href="http://creativecommons.org/licenses/by-nc/3.0/it/deed.it">Creative
		   Commons Attribution 3.0 License - NOT COMMERCIAL</a>.


          </div>
            -->

          <div class="col-md-5">
            <div class="footer-banner">
              <h3 class="footer-title">Development Team</h3>
              <ul>

                <li>Jirapa L.</li>
                <li>Pimpisa W.</li>
                <li>Chusanart P</li>

              </ul>

            </div>
          </div>
        </div>
      </div>
    </footer>

    <!-- JavaScript -->
    <script src="{% static 'js/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
	<script src="{% static 'js/owl.carousel.js' %}"></script>
	<script src="{% static 'js/script.js' %}"></script>
	<!-- StikyMenu -->
	<script src="{% static 'js/stickUp.min.js' %}"></script>

	<script type="text/javascript">
	  jQuery(function($) {
		$(document).ready( function() {
		  $('.navbar-default').stickUp();

		});
	  });
	</script>


	<!-- Smoothscroll -->
	<script type="text/javascript" src="{% static 'js/jquery.corner.js' %}"></script>
	<script src="{% static 'js/wow.min.js' %}"></script>
	<script>
	 new WOW().init();
	</script>
	<script src="{% static 'js/classie.js' %}"></script>
	<script src="{% static 'js/uiMorphingButton_inflow.js' %}"></script>
	<!-- Magnific Popup core JS file -->
	<script src="{% static 'js/jquery.magnific-popup.js' %}"></script>
</body>
<!---->
</html>

workflows/templates/workflows/base_visitor.html
 <!-- FlatFy Theme - Andrea Galanti /-->
<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if IE 9]>    <html class="no-js ie9" lang="en"> <![endif]-->
<!--[if gt IE 9]><!-->
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="Flatfy Free Flat and Responsive HTML5 Template ">
    <meta name="author" content="">

    <title>Workflows – An automate workflows engine for everyone!</title>

    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom Google Web Font -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Arvo:400,700' rel='stylesheet' type='text/css'>

    <!-- Custom CSS-->
     <link href="{% static 'css/general.css' %}" rel="stylesheet">

	 <!-- Owl-Carousel -->
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
	<link href="{% static 'css/owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'css/owl.theme.css' %}" rel="stylesheet">
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
	<link href="{% static 'css/animate.css' %}" rel="stylesheet">

	<!-- Magnific Popup core CSS file -->
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

	<script src="{% static 'js/modernizr-2.8.3.min.js' %}"></script>   <!-- Modernizr /-->
	<!--[if IE 9]>
		<script src="js/PIE_IE9.js"></script>
	<![endif]-->
	<!--[if lt IE 9]>
		<script src="js/PIE_IE678.js"></script>
	<![endif]-->

	<!--[if lt IE 9]>
		<script src="js/html5shiv.js"></script>
	<![endif]-->


    <style>

.navbar-default
{
   position: fixed;
   top: 0px;
}

    </style>

</head>

<body id="home">

	<!-- Preloader -->
	<div id="preloader">
		<div id="status"></div>
	</div>

	<!-- NavBar-->
	<nav class="navbar-default" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'workflows:register' %}">Workflow engine</a>
			</div>

			<div class="collapse navbar-collapse navbar-right navbar-ex1-collapse">
				<ul class="nav navbar-nav">

                    <li class="menuItem"><a href="#signup">Sign up</a></li>

					<li class="menuItem"><a href="{% url 'workflows:login_user' %}">Sign in</a></li>



				</ul>
			</div>

		</div>
	</nav>


	<!-- FullScreen -->
   {% block body %}
	{% endblock %}



	<!-- Banner Download -->
	<!--

	<div id="downloadlink" class="banner">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-md-offset-3 text-center wrap_title">
				<h2>Download Free</h2>
				<p class="lead" style="margin-top:0">Pay with a Tweet</p>
				<p><a class="btn btn-embossed btn-primary view" role="button">Free Download</a></p>
			 </div>
			</div>
		</div>
	</div>
	-->

    <footer>

      <div class="container">
        <div class="row">

            <!--
          <div class="col-md-7">


            <h3 class="footer-title">Follow Me!</h3>
            <p>Vuoi ricevere news su altri template?<br/>
              Visita Andrea Galanti.it e vedrai tutte le news riguardanti nuovi Theme!<br/>
              Go to: <a  href="http://andreagalanti.it" target="_blank">andreagalanti.it</a>
            </p>


			<a rel="cc:attributionURL" href="http://www.andreagalanti.it/flatfy"
		   property="dc:title">Flatfy Theme </a> by
		   <a rel="dc:creator" href="http://www.andreagalanti.it"
		   property="cc:attributionName">Andrea Galanti</a>
		   is licensed to the public under
		   <BR>the <a rel="license"
		   href="http://creativecommons.org/licenses/by-nc/3.0/it/deed.it">Creative
		   Commons Attribution 3.0 License - NOT COMMERCIAL</a>.


          </div>
            -->

          <div class="col-md-5">
            <div class="footer-banner">
              <h3 class="footer-title">TEAM</h3>
              <ul>

                <li>Jirapa L.</li>
                <li>Pimpisa W.</li>
                <li>Chusanart P</li>

              </ul>

            </div>
          </div>
        </div>
      </div>
    </footer>

    <!-- JavaScript -->
    <script src="{% static 'js/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
	<script src="{% static 'js/owl.carousel.js' %}"></script>
	<script src="{% static 'js/script.js' %}"></script>
	<!-- StikyMenu -->
	<script src="{% static 'js/stickUp.min.js' %}"></script>

	<script type="text/javascript">
	  jQuery(function($) {
		$(document).ready( function() {
		  $('.navbar-default').stickUp();

		});
	  });
	</script>


	<!-- Smoothscroll -->
	<script type="text/javascript" src="{% static 'js/jquery.corner.js' %}"></script>
	<script src="{% static 'js/wow.min.js' %}"></script>
	<script>
	 new WOW().init();
	</script>
	<script src="{% static 'js/classie.js' %}"></script>
	<script src="{% static 'js/uiMorphingButton_inflow.js' %}"></script>
	<!-- Magnific Popup core JS file -->
	<script src="{% static 'js/jquery.magnific-popup.js' %}"></script>
</body>
<!---->
</html>

workflows/templates/workflows/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

workflows/templates/workflows/index.html
{% extends 'workflows/base.html' %}
{% block title %}Welcome {{ user.username }}! {% endblock %}
{% block body %}
    {% load staticfiles %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
    <title>Main</title>
    <!--REQUIRED STYLE SHEETS-->
    <!-- BOOTSTRAP CORE STYLE CSS -->

       <!-- CUSTOM STYLE CSS -->

    <!-- GOOGLE FONT -->

    <link href="http://fonts.googleapis.com/css?family=Montserrat" rel='stylesheet' type='text/css'>

    <!-- ICON -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">


<style>

table{
    margin-left: 130px;
    float: left;
    padding: 15px;
}
  td {
      border: 10px solid white;
  }
button {
    margin-top: 20px;
    margin-bottom: 30px;
    background-color: #4CAF50; /* Green */
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    display: inline-block;
    font-size: 16px;
    position:relative;
    left: 45%;
}
img{
   padding: 5px;
}
h2 {
    margin-top: 60px;
    margin-left: 150px;
    line-height:50px;
}
p{
    padding-left: 150px;
    font-size: 30px;
    line-height:50px;
}



</style>


<div class="content-section-a">

        <div class="container">
            <div class="row" style = "left:10%">


   <h4 class="section-heading">Most Popular Apps</h4>

    <table>
      <tr>
        <td width = "150" height = "150" bgcolor = "#93c47d" align="center"><a href="{% url 'workflows:job' %}"><img src=" {% static 'image/Employee.png' %}"><h5>Job Application</h5></a></td>
        <td width = "150" height = "150" bgcolor = "#78909c" align="center"><a href="#2"><img src=" {% static 'image/PalmTree.png' %}"><h5>Vacation Request</h5></a></td>
        <td width = "150" height = "150" bgcolor = "#f7b600" align="center"><a href="#3"><img src=" {% static 'image/Cart.png' %}"><h5>Project Submitting</h5></a></td>
        <td width = "150" height = "150" bgcolor = "#de445e" align="center"><a href="#4"><img src="{% static 'image/Trolley.png' %}"><h5>Business Meeting</h5></a></td>
        <td width = "150" height = "150" bgcolor = "#0097a7" align="center"><a href="{% url 'workflows:announce' %}"><img src="{% static 'image/Receipt.png' %}"><h5>News Posting</h5></a></td>
        <td width = "150" height = "150" bgcolor = "#93c47d" align="center"><a href="{% url 'workflows:funding' %}"><img src="{% static 'image/Bills.png' %}"><h5>Funding</h5></a></td>
        <td width = "150" height = "150" bgcolor = "whitesmoke" align="center"><a href="{% url 'workflows:create' %}"><img src="{% static 'image/Plus.png' %}"><h5>Create your own App</h5></a></td>

      </tr>
    </table>

    <div class = "button">
          <button>SHOW MORE</button>
    </div>

                </div>
        </div>
</div>

<div class="content-section-b">

        <div class="container">
            <div class="row">
            <h4 class="section-heading">Your Workflow(s)</h4>

                {% if workflows %}
                    <table>
                        <tr>

                    {% for workflow in workflows %}

                        <td width = "150" height = "150" bgcolor = "#de445e" align="center"><a href="{% url 'workflows:editWorkflow' workflow.id %}"><img src="{% static 'img/file.png' %}"><h5>{{ workflow.name}}</h5></a></td>

                    {% endfor %}
                        </tr>

                    </table>
                {% else %}
                    <p class="lead">You have not created any workflow yet</p>
                {% endif %}


                </div>
        </div>
</div>


        <!-- JavaScript -->
    <script src="{% static 'js/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
	<script src="{% static 'js/owl.carousel.js' %}"></script>
	<script src="{% static 'js/script.js' %}"></script>

    <!-- JAVASCRIPT FILES PLACED AT THE BOTTOM TO REDUCE THE LOADING TIME  -->
    <!-- CORE JQUERY  -->
    <script src="{% static 'assets/plugins/jquery-1.10.2.js' %}"></script>
    <!-- BOOTSTRAP CORE SCRIPT   -->
    <script src="{% static 'assets/plugins/bootstrap.js' %}"></script>

    <!-- CUSTOM SCRIPTS -->
    <script src="{%static 'assets/js/custom.js' %}"></script>
{% endblock %}